# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=10)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('attribute', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('roll_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='xyz', max_length=100, null=True)),
                ('branch', models.CharField(blank=True, default='xyz', max_length=5, null=True)),
                ('semester', models.CharField(blank=True, default='xyz', max_length=4, null=True)),
                ('year', models.CharField(blank=True, default='xyz', max_length=5, null=True)),
                ('role', models.CharField(blank=True, default='xyz', max_length=20, null=True)),
                ('email', models.CharField(blank=True, default='xyz', max_length=40, null=True)),
                ('mobile', models.CharField(blank=True, default='xyz', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, default='xyz', max_length=10, null=True)),
            ],
        ),
    ]
