# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtable',
            name='position',
            field=models.CharField(blank=True, default='Not Played Yet', max_length=10, null=True),
        ),
    ]
