# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('roll_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=5)),
                ('semester', models.CharField(max_length=4)),
                ('year', models.CharField(max_length=5)),
                ('event', models.CharField(max_length=30)),
                ('position', models.IntegerField(max_length=10)),
                ('attribute_event', models.CharField(max_length=30)),
            ],
        ),
    ]
