# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0002_auto_20180112_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(blank=True, default='Default', max_length=10, null=True),
        ),
    ]
