# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0002_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='position',
            field=models.IntegerField(),
        ),
    ]
