# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0003_studentprofile_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollNo',
            fields=[
                ('roll_no', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
