# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0003_auto_20180108_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='attribute_event',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='event',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
