# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0004_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollno',
            name='roll_no',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
