# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0005_auto_20180108_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
