# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0007_auto_20180206_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='event_type',
        ),
    ]
