# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0008_remove_studentprofile_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='event_type',
            field=models.CharField(blank=True, default='Athletic Meet', max_length=10, null=True),
        ),
    ]
