# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0009_studentprofile_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='event_year',
            field=models.CharField(blank=True, default='NULL', max_length=10, null=True),
        ),
    ]
