# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0010_studentprofile_event_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtable',
            name='event_type',
            field=models.CharField(blank=True, default='Athletic Meet', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='event_year',
            field=models.CharField(blank=True, default='2018', max_length=10, null=True),
        ),
    ]
