# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0011_auto_20180207_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollno',
            name='fatherName',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
